[
    {
        "id": "32896668382",
        "type": "WatchEvent",
        "actor": {
            "id": 6318449,
            "login": "drmats",
            "display_login": "drmats",
            "gravatar_id": "",
            "url": "https://api.github.com/users/drmats",
            "avatar_url": "https://avatars.githubusercontent.com/u/6318449?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T11:09:58Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32896170801",
        "type": "WatchEvent",
        "actor": {
            "id": 4371385,
            "login": "dch1314",
            "display_login": "dch1314",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dch1314",
            "avatar_url": "https://avatars.githubusercontent.com/u/4371385?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T10:49:21Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32892824054",
        "type": "WatchEvent",
        "actor": {
            "id": 113097833,
            "login": "daheitian",
            "display_login": "daheitian",
            "gravatar_id": "",
            "url": "https://api.github.com/users/daheitian",
            "avatar_url": "https://avatars.githubusercontent.com/u/113097833?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T08:41:12Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32892613269",
        "type": "WatchEvent",
        "actor": {
            "id": 14841399,
            "login": "jhaand",
            "display_login": "jhaand",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jhaand",
            "avatar_url": "https://avatars.githubusercontent.com/u/14841399?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T08:33:01Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32892119419",
        "type": "WatchEvent",
        "actor": {
            "id": 17747467,
            "login": "vxacezxcv",
            "display_login": "vxacezxcv",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vxacezxcv",
            "avatar_url": "https://avatars.githubusercontent.com/u/17747467?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T08:13:54Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32890950818",
        "type": "WatchEvent",
        "actor": {
            "id": 30465925,
            "login": "AILTY",
            "display_login": "AILTY",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AILTY",
            "avatar_url": "https://avatars.githubusercontent.com/u/30465925?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T07:25:39Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32889691883",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 33387350,
            "login": "bvndls",
            "display_login": "bvndls",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bvndls",
            "avatar_url": "https://avatars.githubusercontent.com/u/33387350?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4965",
                "id": 1954492603,
                "node_id": "I_kwDOH1Ppo850fzC7",
                "number": 4965,
                "title": "[bug]: memref<1x1x77x77xi1>, Program Inference error on Apple M1",
                "user": {
                    "login": "bvndls",
                    "id": 33387350,
                    "node_id": "MDQ6VXNlcjMzMzg3MzUw",
                    "avatar_url": "https://avatars.githubusercontent.com/u/33387350?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/bvndls",
                    "html_url": "https://github.com/bvndls",
                    "followers_url": "https://api.github.com/users/bvndls/followers",
                    "following_url": "https://api.github.com/users/bvndls/following{/other_user}",
                    "gists_url": "https://api.github.com/users/bvndls/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/bvndls/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/bvndls/subscriptions",
                    "organizations_url": "https://api.github.com/users/bvndls/orgs",
                    "repos_url": "https://api.github.com/users/bvndls/repos",
                    "events_url": "https://api.github.com/users/bvndls/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/bvndls/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-20T15:09:30Z",
                "updated_at": "2023-10-27T06:24:59Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### OS\r\n\r\nmacOS\r\n\r\n### GPU\r\n\r\nmps\r\n\r\n### VRAM\r\n\r\n7.5GB\r\n\r\n### What version did you experience this issue on?\r\n\r\n3.3.0post3\r\n\r\n### What happened?\r\n\r\n>Note: A similar issue was found on (https://github.com/invoke-ai/InvokeAI/issues/4356), but it differs in many ways\r\n\r\nAfter successfully generating a 512x512 image in the Workflow Editor using Dreamshaper, I've changed the output resolution to 1024x1024 and got this error.\r\nChanging the resolution back to 512x512, changing the model, updating to v3.4.0rc1 or reinstalling InvokeAI using install.sh didn't fix the issue.\r\n\r\n\r\n# Steps to reproduce\r\n1. Install InvokeAI using the __install.sh script__\r\n\r\nLogs:\r\n````bash\r\n\u279c  InvokeAI-Installer ./install.sh\r\nInitializing the installer. This may take a minute - please wait...\r\n\r\n[notice] A new release of pip is available: 23.2.1 -> 23.3\r\n[notice] To update, run: /private/var/folders/s4/ktq1zp391_v8vlcd1dk5pylc0000gn/T/invokeai-installer-tmpej7olhkb/bin/python3.11 -m pip install --upgrade pip\r\n\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\r\n\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 Welcome to the InvokeAI Installer \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\r\n\u2551                                                                                                                                                                                                                                     \u2551\r\n\u2551  macOS Users!                                                                                                                                                                                                                       \u2551\r\n\u2551                                                                                                                                                                                                                                     \u2551\r\n\u2551  Please be sure you have the Xcode command-line tools installed before continuing.                                                                                                                                                  \u2551\r\n\u2551  If not, cancel with Control-C and follow the Xcode install instructions at https://www.freecodecamp.org/news/install-xcode-command-line-tools/.                                                                                    \u2551\r\n\u2551                                                                                                                                                                                                                                     \u2551\r\n\u2551                            Some of the installation steps take a long time to run. Please be patient. If the script appears to hang for more than 10 minutes, please interrupt with Control-C and retry.                            \u2551\r\n\u2551                                                                                                                                                                                                                                     \u2551\r\n\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 Darwin-arm64 \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d\r\n\r\n\u2757 Directory /Users/bvndls/invokeai already exists \u2757\r\n\ud83d\uded1 (re)install in this location? [y/n] (n): y\r\n\r\nYour platform Darwin-arm64 only supports the \"cpu\" driver. Proceeding with that.\r\n````\r\n>Followed by __Installing PyTorch \ud83d\udd25__ and __Installing the InvokeAI Application \ud83c\udfa8__ sections (no errors)\r\n\r\n2. Manually configure the exact way as shown here: <img width=\"1754\" alt=\"invokeai-config\" src=\"https://github.com/invoke-ai/InvokeAI/assets/33387350/e2d2d23b-591c-48a2-995a-e207891a894b\">\r\n\r\n3. Launch the web interface\r\n\r\nLogs:\r\n````bash\r\nPlease enter 1-11, Q: [1] 1\r\nGenerate images with a browser-based interface\r\n[2023-10-20 16:44:16,819]::[InvokeAI]::INFO --> Loaded 0 modules from /Users/bvndls/invokeai/nodes\r\n/Users/bvndls/invokeai/.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.\r\n  warnings.warn(\r\n>> patchmatch.patch_match: INFO - Compiling and loading c extensions from \"/Users/bvndls/invokeai/.venv/lib/python3.11/site-packages/patchmatch\".\r\n>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).\r\n>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.\r\n[2023-10-20 16:44:20,021]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)\r\n[2023-10-20 16:44:21,466]::[uvicorn.error]::INFO --> Started server process [13067]\r\n[2023-10-20 16:44:21,466]::[uvicorn.error]::INFO --> Waiting for application startup.\r\n[2023-10-20 16:44:21,466]::[InvokeAI]::INFO --> InvokeAI version 3.4.0rc1\r\n[2023-10-20 16:44:21,466]::[InvokeAI]::INFO --> Root directory = /Users/bvndls/invokeai\r\n[2023-10-20 16:44:21,466]::[InvokeAI]::INFO --> Using database at /Users/bvndls/invokeai/databases/invokeai.db\r\n[2023-10-20 16:44:21,473]::[InvokeAI]::INFO --> GPU device = mps\r\n[2023-10-20 16:44:21,476]::[InvokeAI]::INFO --> Scanning /Users/bvndls/invokeai/models for new models\r\n[2023-10-20 16:44:21,618]::[InvokeAI]::INFO --> Scanned 9 files and directories, imported 0 models\r\n[2023-10-20 16:44:21,620]::[InvokeAI]::INFO --> Model manager service initialized\r\n[2023-10-20 16:44:21,635]::[InvokeAI]::INFO --> Pruned 1 finished queue items\r\n[2023-10-20 16:44:21,641]::[InvokeAI]::INFO --> Cleaned database\r\n[2023-10-20 16:44:21,641]::[uvicorn.error]::INFO --> Application startup complete.\r\n[2023-10-20 16:44:21,641]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)\r\n````\r\n\r\n4. Upload [Workflow.json](https://github.com/invoke-ai/InvokeAI/files/13055546/Workflow.json) and add to queue\r\n\r\nLogs:\r\n````bash\r\n[2023-10-20 16:53:47,303]::[InvokeAI]::INFO --> Loading model /Users/bvndls/invokeai/models/.cache/ef2ecfad56d695bd9086861664706992, type sd-1:main:tokenizer\r\n[2023-10-20 16:53:48,425]::[InvokeAI]::INFO --> Loading model /Users/bvndls/invokeai/models/.cache/ef2ecfad56d695bd9086861664706992, type sd-1:main:text_encoder\r\nloc(\"cast\"(\"(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm\":745:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<1x1x77x77xi1>'\r\n[2023-10-20 16:53:54,598]::[InvokeAI]::INFO --> Loading model /Users/bvndls/invokeai/models/.cache/ef2ecfad56d695bd9086861664706992, type sd-1:main:unet\r\n[2023-10-20 16:54:09,906]::[InvokeAI]::INFO --> Loading model /Users/bvndls/invokeai/models/.cache/ef2ecfad56d695bd9086861664706992, type sd-1:main:scheduler\r\n  0%|                                                                                                                                                                                                           | 0/10 [00:00<?, ?it/s]2023-10-20 16:54:14.258 Python[13067:396710] ANE Evaluation Error = Error Domain=com.apple.appleneuralengine Code=8 \"processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error\" UserInfo={NSLocalizedDescription=processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error}\r\n2023-10-20 16:54:14.258 Python[13067:396710] ANE Scheduling Error = Error Domain=com.apple.appleneuralengine Code=8 \"processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error\" UserInfo={NSLocalizedDescription=processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error}\r\n2023-10-20 16:54:14.263 Python[13067:396710] ANE Evaluation Error = Error Domain=com.apple.appleneuralengine Code=8 \"processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error\" UserInfo={NSLocalizedDescription=processRequest:model:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0x16 : statusType=0x9: Program Inference error}\r\n````\r\nLast string repeats over and over until the webui is down\r\nCurrent Image Shows a black image after generating the noise\r\n\r\n### Screenshots\r\n\r\n<img width=\"1754\" alt=\"image\" src=\"https://github.com/invoke-ai/InvokeAI/assets/33387350/2986a578-e4ea-4548-82f0-6db62d3a4f74\">\r\n<img width=\"1754\" alt=\"image\" src=\"https://github.com/invoke-ai/InvokeAI/assets/33387350/fd8886c0-069a-4b2c-8627-b045e120d1cd\">\r\n<img width=\"1760\" alt=\"image\" src=\"https://github.com/invoke-ai/InvokeAI/assets/33387350/04228f28-d52d-4e81-9222-c0b41ee7c3c1\">\r\n\r\n\r\n### Additional context\r\n\r\n ## The first run right after installation\r\n >the same settings - 7.5GB, mps, sliced attention and etc.\r\n\r\n![tg_image_3684351740](https://github.com/invoke-ai/InvokeAI/assets/33387350/bd2f60eb-904a-472c-a4ff-d6286c7c5bcb)\r\n\r\n\r\n\r\n### Contact Details\r\n\r\n[Telegram](https://t.me/bvndls0), pm@bvndls.com",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782365804",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4965#issuecomment-1782365804",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4965",
                "id": 1782365804,
                "node_id": "IC_kwDOH1Ppo85qPL5s",
                "user": {
                    "login": "bvndls",
                    "id": 33387350,
                    "node_id": "MDQ6VXNlcjMzMzg3MzUw",
                    "avatar_url": "https://avatars.githubusercontent.com/u/33387350?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/bvndls",
                    "html_url": "https://github.com/bvndls",
                    "followers_url": "https://api.github.com/users/bvndls/followers",
                    "following_url": "https://api.github.com/users/bvndls/following{/other_user}",
                    "gists_url": "https://api.github.com/users/bvndls/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/bvndls/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/bvndls/subscriptions",
                    "organizations_url": "https://api.github.com/users/bvndls/orgs",
                    "repos_url": "https://api.github.com/users/bvndls/repos",
                    "events_url": "https://api.github.com/users/bvndls/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/bvndls/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-27T06:24:58Z",
                "updated_at": "2023-10-27T06:24:58Z",
                "author_association": "NONE",
                "body": "https://github.com/pytorch/pytorch/issues/104642 this may be useful",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782365804/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-27T06:24:59Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32886817180",
        "type": "WatchEvent",
        "actor": {
            "id": 30212149,
            "login": "mymmyy",
            "display_login": "mymmyy",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mymmyy",
            "avatar_url": "https://avatars.githubusercontent.com/u/30212149?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-27T02:56:15Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32885106512",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4982",
                "id": 1959185548,
                "node_id": "I_kwDOH1Ppo850xsyM",
                "number": 4982,
                "title": "[enhancement]: DPM++ 3M samplers/schedulers",
                "user": {
                    "login": "Jaid",
                    "id": 6216144,
                    "node_id": "MDQ6VXNlcjYyMTYxNDQ=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/6216144?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Jaid",
                    "html_url": "https://github.com/Jaid",
                    "followers_url": "https://api.github.com/users/Jaid/followers",
                    "following_url": "https://api.github.com/users/Jaid/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Jaid/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Jaid/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Jaid/subscriptions",
                    "organizations_url": "https://api.github.com/users/Jaid/orgs",
                    "repos_url": "https://api.github.com/users/Jaid/repos",
                    "events_url": "https://api.github.com/users/Jaid/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Jaid/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402085,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY5Q",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/enhancement",
                        "name": "enhancement",
                        "color": "a2eeef",
                        "default": true,
                        "description": "New feature or request"
                    },
                    {
                        "id": 5817593882,
                        "node_id": "LA_kwDOH1Ppo88AAAABWsFwGg",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/image%20generation",
                        "name": "image generation",
                        "color": "6BE2DC",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-24T12:51:23Z",
                "updated_at": "2023-10-27T00:42:11Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### Contact Details\n\nDiscord: jaidchen\n\n### What should this feature add?\n\nComfy and Automatic1111 included new DPM++ 3M samplers/schedulers in their projects that some people reported to perform slightly better for high-steps high-details creations.\r\n\r\nAny chance to see them in one of the next releases?\r\n\r\n---\r\n\r\n- Automatic1111\r\n- - https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ef669de080814067961f28357256e8fe27544f4/CHANGELOG.md?plain=1#L9\r\n- - https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ef669de080814067961f28357256e8fe27544f4/modules/sd_samplers_kdiffusion.py#L29-L31\r\n- Comfy\r\n- - https://github.com/comfyanonymous/ComfyUI/blob/b935bea3a0201221eca7b0337bc60a329871300a/comfy/k_diffusion/sampling.py#L642-L695\r\n\n\n### Alternatives\n\n_No response_\n\n### Additional Content\n\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782122122",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4982#issuecomment-1782122122",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4982",
                "id": 1782122122,
                "node_id": "IC_kwDOH1Ppo85qOQaK",
                "user": {
                    "login": "Millu",
                    "id": 7254508,
                    "node_id": "MDQ6VXNlcjcyNTQ1MDg=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/7254508?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Millu",
                    "html_url": "https://github.com/Millu",
                    "followers_url": "https://api.github.com/users/Millu/followers",
                    "following_url": "https://api.github.com/users/Millu/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Millu/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Millu/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Millu/subscriptions",
                    "organizations_url": "https://api.github.com/users/Millu/orgs",
                    "repos_url": "https://api.github.com/users/Millu/repos",
                    "events_url": "https://api.github.com/users/Millu/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Millu/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-27T00:42:10Z",
                "updated_at": "2023-10-27T00:42:10Z",
                "author_association": "COLLABORATOR",
                "body": "Thanks for sharing! Definitely on our radar, but can't promise it will be in the very next release ",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782122122/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:42:11Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884819166",
        "type": "IssuesEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4963",
                "id": 1954321868,
                "node_id": "I_kwDOH1Ppo850fJXM",
                "number": 4963,
                "title": "[bug]: Problems with IP adapter",
                "user": {
                    "login": "vrubzov1957",
                    "id": 54937209,
                    "node_id": "MDQ6VXNlcjU0OTM3MjA5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/54937209?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/vrubzov1957",
                    "html_url": "https://github.com/vrubzov1957",
                    "followers_url": "https://api.github.com/users/vrubzov1957/followers",
                    "following_url": "https://api.github.com/users/vrubzov1957/following{/other_user}",
                    "gists_url": "https://api.github.com/users/vrubzov1957/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/vrubzov1957/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/vrubzov1957/subscriptions",
                    "organizations_url": "https://api.github.com/users/vrubzov1957/orgs",
                    "repos_url": "https://api.github.com/users/vrubzov1957/repos",
                    "events_url": "https://api.github.com/users/vrubzov1957/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/vrubzov1957/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 2,
                "created_at": "2023-10-20T13:41:58Z",
                "updated_at": "2023-10-27T00:19:48Z",
                "closed_at": "2023-10-27T00:19:48Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### OS\r\n\r\nWindows\r\n\r\n### GPU\r\n\r\ncuda\r\n\r\n### VRAM\r\n\r\n11\r\n\r\n### What version did you experience this issue on?\r\n\r\n3.4.0rc1\r\n\r\n### What happened?\r\n\r\nCan't add IP adapter. But I downloaded it earlier, and I earlier in 3.2.0 I could add and enable IP adapter\r\n\r\n<img width=\"436\" alt=\"ip\" src=\"https://github.com/invoke-ai/InvokeAI/assets/54937209/5652a0e4-6905-47e7-bd15-562cdaa7bbe4\">\r\n\r\nAfter adding IP adapter again from Repo - now I get this error, and IP-adapter not work\r\n```\r\n[2023-10-21 04:41:17,165]::[InvokeAI]::INFO --> Loading model D:\\InvokeAI_3\\models\\any\\clip_vision\\ip_adapter_sd_image_encoder, type any:clip_vision\r\n[2023-10-21 04:41:17,762]::[InvokeAI]::ERROR --> Traceback (most recent call last):\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\invocation_processor\\invocation_processor_default.py\", line 104, in __process\r\n    outputs = invocation.invoke_internal(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\baseinvocation.py\", line 659, in invoke_internal\r\n    output = self.invoke(context)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\latent.py\", line 744, in invoke\r\n    ip_adapter_data = self.prep_ip_adapter_data(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\latent.py\", line 488, in prep_ip_adapter_data\r\n    image_encoder_model_info = context.services.model_manager.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\model_manager\\model_manager_default.py\", line 112, in get_model\r\n    model_info = self.mgr.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_manager.py\", line 496, in get_model\r\n    model_context = self.cache.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_cache.py\", line 228, in get_model\r\n    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\clip_vision.py\", line 63, in get_model\r\n    model = CLIPVisionModelWithProjection.from_pretrained(self.model_path, torch_dtype=torch_dtype)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\transformers\\modeling_utils.py\", line 2629, in from_pretrained\r\n    state_dict = load_state_dict(resolved_archive_file)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\transformers\\modeling_utils.py\", line 447, in load_state_dict\r\n    with safe_open(checkpoint_file, framework=\"pt\") as f:\r\nsafetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer\r\n\r\n[2023-10-21 04:41:17,768]::[InvokeAI]::ERROR --> Error while invoking:\r\nError while deserializing header: MetadataIncompleteBuffer\r\n\r\n```\r\n### Screenshots\r\n\r\n\r\n### Additional context\r\n\r\n_No response_\r\n\r\n### Contact Details\r\n\r\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/timeline",
                "performed_via_github_app": null,
                "state_reason": "not_planned"
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:19:49Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884819111",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4963",
                "id": 1954321868,
                "node_id": "I_kwDOH1Ppo850fJXM",
                "number": 4963,
                "title": "[bug]: Problems with IP adapter",
                "user": {
                    "login": "vrubzov1957",
                    "id": 54937209,
                    "node_id": "MDQ6VXNlcjU0OTM3MjA5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/54937209?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/vrubzov1957",
                    "html_url": "https://github.com/vrubzov1957",
                    "followers_url": "https://api.github.com/users/vrubzov1957/followers",
                    "following_url": "https://api.github.com/users/vrubzov1957/following{/other_user}",
                    "gists_url": "https://api.github.com/users/vrubzov1957/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/vrubzov1957/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/vrubzov1957/subscriptions",
                    "organizations_url": "https://api.github.com/users/vrubzov1957/orgs",
                    "repos_url": "https://api.github.com/users/vrubzov1957/repos",
                    "events_url": "https://api.github.com/users/vrubzov1957/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/vrubzov1957/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 2,
                "created_at": "2023-10-20T13:41:58Z",
                "updated_at": "2023-10-27T00:19:48Z",
                "closed_at": "2023-10-27T00:19:48Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### OS\r\n\r\nWindows\r\n\r\n### GPU\r\n\r\ncuda\r\n\r\n### VRAM\r\n\r\n11\r\n\r\n### What version did you experience this issue on?\r\n\r\n3.4.0rc1\r\n\r\n### What happened?\r\n\r\nCan't add IP adapter. But I downloaded it earlier, and I earlier in 3.2.0 I could add and enable IP adapter\r\n\r\n<img width=\"436\" alt=\"ip\" src=\"https://github.com/invoke-ai/InvokeAI/assets/54937209/5652a0e4-6905-47e7-bd15-562cdaa7bbe4\">\r\n\r\nAfter adding IP adapter again from Repo - now I get this error, and IP-adapter not work\r\n```\r\n[2023-10-21 04:41:17,165]::[InvokeAI]::INFO --> Loading model D:\\InvokeAI_3\\models\\any\\clip_vision\\ip_adapter_sd_image_encoder, type any:clip_vision\r\n[2023-10-21 04:41:17,762]::[InvokeAI]::ERROR --> Traceback (most recent call last):\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\invocation_processor\\invocation_processor_default.py\", line 104, in __process\r\n    outputs = invocation.invoke_internal(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\baseinvocation.py\", line 659, in invoke_internal\r\n    output = self.invoke(context)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\latent.py\", line 744, in invoke\r\n    ip_adapter_data = self.prep_ip_adapter_data(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\latent.py\", line 488, in prep_ip_adapter_data\r\n    image_encoder_model_info = context.services.model_manager.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\model_manager\\model_manager_default.py\", line 112, in get_model\r\n    model_info = self.mgr.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_manager.py\", line 496, in get_model\r\n    model_context = self.cache.get_model(\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_cache.py\", line 228, in get_model\r\n    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\clip_vision.py\", line 63, in get_model\r\n    model = CLIPVisionModelWithProjection.from_pretrained(self.model_path, torch_dtype=torch_dtype)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\transformers\\modeling_utils.py\", line 2629, in from_pretrained\r\n    state_dict = load_state_dict(resolved_archive_file)\r\n  File \"D:\\InvokeAI_3\\.venv\\lib\\site-packages\\transformers\\modeling_utils.py\", line 447, in load_state_dict\r\n    with safe_open(checkpoint_file, framework=\"pt\") as f:\r\nsafetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer\r\n\r\n[2023-10-21 04:41:17,768]::[InvokeAI]::ERROR --> Error while invoking:\r\nError while deserializing header: MetadataIncompleteBuffer\r\n\r\n```\r\n### Screenshots\r\n\r\n\r\n### Additional context\r\n\r\n_No response_\r\n\r\n### Contact Details\r\n\r\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963/timeline",
                "performed_via_github_app": null,
                "state_reason": "not_planned"
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782107165",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4963#issuecomment-1782107165",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4963",
                "id": 1782107165,
                "node_id": "IC_kwDOH1Ppo85qOMwd",
                "user": {
                    "login": "Millu",
                    "id": 7254508,
                    "node_id": "MDQ6VXNlcjcyNTQ1MDg=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/7254508?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Millu",
                    "html_url": "https://github.com/Millu",
                    "followers_url": "https://api.github.com/users/Millu/followers",
                    "following_url": "https://api.github.com/users/Millu/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Millu/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Millu/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Millu/subscriptions",
                    "organizations_url": "https://api.github.com/users/Millu/orgs",
                    "repos_url": "https://api.github.com/users/Millu/repos",
                    "events_url": "https://api.github.com/users/Millu/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Millu/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-27T00:19:48Z",
                "updated_at": "2023-10-27T00:19:48Z",
                "author_association": "COLLABORATOR",
                "body": "Glad you got it fixed! ",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782107165/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:19:48Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884779256",
        "type": "IssuesEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4948",
                "id": 1951453130,
                "node_id": "I_kwDOH1Ppo850UM_K",
                "number": 4948,
                "title": "[bug]: PydanticImportError: BaseSettings has been moved to the pydantic-settings package",
                "user": {
                    "login": "drdancm",
                    "id": 132060667,
                    "node_id": "U_kgDOB98V-w",
                    "avatar_url": "https://avatars.githubusercontent.com/u/132060667?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/drdancm",
                    "html_url": "https://github.com/drdancm",
                    "followers_url": "https://api.github.com/users/drdancm/followers",
                    "following_url": "https://api.github.com/users/drdancm/following{/other_user}",
                    "gists_url": "https://api.github.com/users/drdancm/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/drdancm/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/drdancm/subscriptions",
                    "organizations_url": "https://api.github.com/users/drdancm/orgs",
                    "repos_url": "https://api.github.com/users/drdancm/repos",
                    "events_url": "https://api.github.com/users/drdancm/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/drdancm/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    },
                    {
                        "id": 4727253590,
                        "node_id": "LA_kwDOH1Ppo88AAAABGcQqVg",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/install",
                        "name": "install",
                        "color": "F96F0E",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-19T07:09:38Z",
                "updated_at": "2023-10-27T00:16:40Z",
                "closed_at": "2023-10-27T00:16:40Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### OS\n\nWindows\n\n### GPU\n\ncuda\n\n### VRAM\n\n12Gb\n\n### What version did you experience this issue on?\n\nxx.xx.xx\n\n### What happened?\n\nWhen Invoke starts it does not give version. Nor can I find it anywhere. I've running Invoke inside Stability Matrix.\r\nFirst version I had ran fine, but subsequent updates ( I lose count, but at least 5 Update notices) which I ran crash. Here is what latest update gave me:\r\n\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 2, in <module>\r\n  File \"D:\\STABLEDIFF\\Data\\Packages\\InvokeAI\\venv\\lib\\site-packages\\invokeai\\app\\api_app.py\", line 1, in <module>\r\n    from .services.config import InvokeAIAppConfig\r\n  File \"D:\\STABLEDIFF\\Data\\Packages\\InvokeAI\\venv\\lib\\site-packages\\invokeai\\app\\services\\config\\__init__.py\", line 5, in <module>\r\n    from .config_base import PagingArgumentParser  # noqa F401\r\n  File \"D:\\STABLEDIFF\\Data\\Packages\\InvokeAI\\venv\\lib\\site-packages\\invokeai\\app\\services\\config\\config_base.py\", line 21, in <module>\r\n    from pydantic import BaseSettings\r\n  File \"D:\\STABLEDIFF\\Data\\Packages\\InvokeAI\\venv\\lib\\site-packages\\pydantic\\__init__.py\", line 218, in __getattr__\r\n    return _getattr_migration(attr_name)\r\n  File \"D:\\STABLEDIFF\\Data\\Packages\\InvokeAI\\venv\\lib\\site-packages\\pydantic\\_migration.py\", line 294, in wrapper\r\n    raise PydanticImportError(\r\npydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.\r\n\r\nFor further information visit https://errors.pydantic.dev/2.4/u/import-error\r\n\r\nProcess finished with exit code 1\n\n### Screenshots\n\nsee above\n\n### Additional context\n\nInside Stability Matrix. Haven't searched for existing issue because I'm not sure how to describe the problem.\n\n### Contact Details\n\ndrdancm@computersandfood.com",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4948/timeline",
                "performed_via_github_app": null,
                "state_reason": "not_planned"
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:16:41Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884695126",
        "type": "IssuesEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4988",
                "id": 1964075449,
                "node_id": "I_kwDOH1Ppo851EWm5",
                "number": 4988,
                "title": "[bug]: sorry not a bug but, congrats people invoke ai also banned from colab",
                "user": {
                    "login": "ShashwatDubey99",
                    "id": 90603919,
                    "node_id": "MDQ6VXNlcjkwNjAzOTE5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/90603919?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ShashwatDubey99",
                    "html_url": "https://github.com/ShashwatDubey99",
                    "followers_url": "https://api.github.com/users/ShashwatDubey99/followers",
                    "following_url": "https://api.github.com/users/ShashwatDubey99/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ShashwatDubey99/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ShashwatDubey99/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ShashwatDubey99/subscriptions",
                    "organizations_url": "https://api.github.com/users/ShashwatDubey99/orgs",
                    "repos_url": "https://api.github.com/users/ShashwatDubey99/repos",
                    "events_url": "https://api.github.com/users/ShashwatDubey99/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ShashwatDubey99/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-26T18:01:55Z",
                "updated_at": "2023-10-27T00:10:09Z",
                "closed_at": "2023-10-27T00:10:08Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### OS\n\nLinux\n\n### GPU\n\ncuda\n\n### VRAM\n\n_No response_\n\n### What version did you experience this issue on?\n\n3.4..Orc1\n\n### What happened?\n\nI think because of the so called you tuber who promoted invoke colab the invoke ai colab got also banned, it was already suspected as the sd webui and comfy ui \n\n### Screenshots\n\n![IMG-20231026-WA0001](https://github.com/invoke-ai/InvokeAI/assets/90603919/b3f08d31-49bd-49b8-aa50-43216cfafdb8)\r\n\n\n### Additional context\n\n_No response_\n\n### Contact Details\n\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/timeline",
                "performed_via_github_app": null,
                "state_reason": "not_planned"
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:10:10Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884695030",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 7254508,
            "login": "Millu",
            "display_login": "Millu",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Millu",
            "avatar_url": "https://avatars.githubusercontent.com/u/7254508?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4988",
                "id": 1964075449,
                "node_id": "I_kwDOH1Ppo851EWm5",
                "number": 4988,
                "title": "[bug]: sorry not a bug but, congrats people invoke ai also banned from colab",
                "user": {
                    "login": "ShashwatDubey99",
                    "id": 90603919,
                    "node_id": "MDQ6VXNlcjkwNjAzOTE5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/90603919?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ShashwatDubey99",
                    "html_url": "https://github.com/ShashwatDubey99",
                    "followers_url": "https://api.github.com/users/ShashwatDubey99/followers",
                    "following_url": "https://api.github.com/users/ShashwatDubey99/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ShashwatDubey99/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ShashwatDubey99/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ShashwatDubey99/subscriptions",
                    "organizations_url": "https://api.github.com/users/ShashwatDubey99/orgs",
                    "repos_url": "https://api.github.com/users/ShashwatDubey99/repos",
                    "events_url": "https://api.github.com/users/ShashwatDubey99/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ShashwatDubey99/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-26T18:01:55Z",
                "updated_at": "2023-10-27T00:10:09Z",
                "closed_at": "2023-10-27T00:10:08Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### OS\n\nLinux\n\n### GPU\n\ncuda\n\n### VRAM\n\n_No response_\n\n### What version did you experience this issue on?\n\n3.4..Orc1\n\n### What happened?\n\nI think because of the so called you tuber who promoted invoke colab the invoke ai colab got also banned, it was already suspected as the sd webui and comfy ui \n\n### Screenshots\n\n![IMG-20231026-WA0001](https://github.com/invoke-ai/InvokeAI/assets/90603919/b3f08d31-49bd-49b8-aa50-43216cfafdb8)\r\n\n\n### Additional context\n\n_No response_\n\n### Contact Details\n\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/timeline",
                "performed_via_github_app": null,
                "state_reason": "not_planned"
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782098880",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4988#issuecomment-1782098880",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988",
                "id": 1782098880,
                "node_id": "IC_kwDOH1Ppo85qOKvA",
                "user": {
                    "login": "Millu",
                    "id": 7254508,
                    "node_id": "MDQ6VXNlcjcyNTQ1MDg=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/7254508?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Millu",
                    "html_url": "https://github.com/Millu",
                    "followers_url": "https://api.github.com/users/Millu/followers",
                    "following_url": "https://api.github.com/users/Millu/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Millu/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Millu/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Millu/subscriptions",
                    "organizations_url": "https://api.github.com/users/Millu/orgs",
                    "repos_url": "https://api.github.com/users/Millu/repos",
                    "events_url": "https://api.github.com/users/Millu/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Millu/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-27T00:10:08Z",
                "updated_at": "2023-10-27T00:10:08Z",
                "author_association": "COLLABORATOR",
                "body": "Thanks for flagging!",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1782098880/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-27T00:10:09Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884202455",
        "type": "WatchEvent",
        "actor": {
            "id": 17361,
            "login": "shanev",
            "display_login": "shanev",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shanev",
            "avatar_url": "https://avatars.githubusercontent.com/u/17361?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T23:29:53Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32884048618",
        "type": "WatchEvent",
        "actor": {
            "id": 33495454,
            "login": "carlosnani",
            "display_login": "carlosnani",
            "gravatar_id": "",
            "url": "https://api.github.com/users/carlosnani",
            "avatar_url": "https://avatars.githubusercontent.com/u/33495454?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T23:17:19Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32883846749",
        "type": "WatchEvent",
        "actor": {
            "id": 103886366,
            "login": "Suzuki-Kame",
            "display_login": "Suzuki-Kame",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Suzuki-Kame",
            "avatar_url": "https://avatars.githubusercontent.com/u/103886366?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T23:02:08Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32880500511",
        "type": "WatchEvent",
        "actor": {
            "id": 36376725,
            "login": "pagarsky",
            "display_login": "pagarsky",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pagarsky",
            "avatar_url": "https://avatars.githubusercontent.com/u/36376725?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T20:01:27Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32877683456",
        "type": "IssuesEvent",
        "actor": {
            "id": 90603919,
            "login": "ShashwatDubey99",
            "display_login": "ShashwatDubey99",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ShashwatDubey99",
            "avatar_url": "https://avatars.githubusercontent.com/u/90603919?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4988",
                "id": 1964075449,
                "node_id": "I_kwDOH1Ppo851EWm5",
                "number": 4988,
                "title": "[bug]: sorry not a bug but, congrats people invoke ai also banned from colab",
                "user": {
                    "login": "ShashwatDubey99",
                    "id": 90603919,
                    "node_id": "MDQ6VXNlcjkwNjAzOTE5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/90603919?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ShashwatDubey99",
                    "html_url": "https://github.com/ShashwatDubey99",
                    "followers_url": "https://api.github.com/users/ShashwatDubey99/followers",
                    "following_url": "https://api.github.com/users/ShashwatDubey99/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ShashwatDubey99/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ShashwatDubey99/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ShashwatDubey99/subscriptions",
                    "organizations_url": "https://api.github.com/users/ShashwatDubey99/orgs",
                    "repos_url": "https://api.github.com/users/ShashwatDubey99/repos",
                    "events_url": "https://api.github.com/users/ShashwatDubey99/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ShashwatDubey99/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-26T18:01:55Z",
                "updated_at": "2023-10-26T18:01:55Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### OS\n\nLinux\n\n### GPU\n\ncuda\n\n### VRAM\n\n_No response_\n\n### What version did you experience this issue on?\n\n3.4..Orc1\n\n### What happened?\n\nI think because of the so called you tuber who promoted invoke colab the invoke ai colab got also banned, it was already suspected as the sd webui and comfy ui \n\n### Screenshots\n\n![IMG-20231026-WA0001](https://github.com/invoke-ai/InvokeAI/assets/90603919/b3f08d31-49bd-49b8-aa50-43216cfafdb8)\r\n\n\n### Additional context\n\n_No response_\n\n### Contact Details\n\n_No response_",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4988/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-26T18:01:57Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32876108828",
        "type": "WatchEvent",
        "actor": {
            "id": 6153433,
            "login": "b0xtch",
            "display_login": "b0xtch",
            "gravatar_id": "",
            "url": "https://api.github.com/users/b0xtch",
            "avatar_url": "https://avatars.githubusercontent.com/u/6153433?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T16:58:05Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32874242090",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 126418078,
            "login": "gingerkrueger",
            "display_login": "gingerkrueger",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gingerkrueger",
            "avatar_url": "https://avatars.githubusercontent.com/u/126418078?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4050",
                "id": 1826741136,
                "node_id": "I_kwDOH1Ppo85s4duQ",
                "number": 4050,
                "title": "[bug]: Adding new XL models gives errors: ",
                "user": {
                    "login": "def1701",
                    "id": 40907624,
                    "node_id": "MDQ6VXNlcjQwOTA3NjI0",
                    "avatar_url": "https://avatars.githubusercontent.com/u/40907624?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/def1701",
                    "html_url": "https://github.com/def1701",
                    "followers_url": "https://api.github.com/users/def1701/followers",
                    "following_url": "https://api.github.com/users/def1701/following{/other_user}",
                    "gists_url": "https://api.github.com/users/def1701/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/def1701/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/def1701/subscriptions",
                    "organizations_url": "https://api.github.com/users/def1701/orgs",
                    "repos_url": "https://api.github.com/users/def1701/repos",
                    "events_url": "https://api.github.com/users/def1701/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/def1701/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    },
                    {
                        "id": 5779838726,
                        "node_id": "LA_kwDOH1Ppo88AAAABWIFXBg",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/SDXL",
                        "name": "SDXL",
                        "color": "FD7C0A",
                        "default": false,
                        "description": "Issues relating to SDXL"
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 5,
                "created_at": "2023-07-28T16:44:08Z",
                "updated_at": "2023-10-26T15:48:57Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### OS\r\n\r\nWindows\r\n\r\n### GPU\r\n\r\ncuda\r\n\r\n### VRAM\r\n\r\n_No response_\r\n\r\n### What version did you experience this issue on?\r\n\r\n3.0.1\r\n\r\n### What happened?\r\n\r\nThere are 2 errors - \r\n1. Error while invoking: 'time_embed.0.weight', this one occurs after adding the XL model and running invoke on any prompt.  This error occurs on models that are smaller than 1 GB.   \r\n\r\n2. Error while invoking: 'ModuleList' object has no attribute '1'\r\nAlso occurs after adding the model and invoking on any prompt.  This error occurs on larger models.  Most were 6gb+\r\n\r\nI have successfully added 3 XL models and about 10+ have failed with one of these two errors.\r\n\r\n3. Using today's release 3.0.1 Post 3 - tries 6 more models,,  anew error is showing in addition to #2194 Error while invoking:\r\n'model.diffusion_model.input_blocks.0.0.bias'\r\n### Screenshots\r\n\r\n_No response_\r\n\r\n### Additional context\r\n\r\nFull error:\r\n============================================================\r\n#1 error\r\n =====================================================\r\n[2023-07-28 08:46:59,688]::[InvokeAI]::ERROR --> Traceback (most recent call last):\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\processor.py\", line 86, in __process\r\n    outputs = invocation.invoke(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\compel.py\", line 352, in invoke\r\n    c1, c1_pooled, ec1 = self.run_clip_compel(context, self.clip, self.prompt, False)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\compel.py\", line 243, in run_clip_compel\r\n    tokenizer_info = context.services.model_manager.get_model(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\model_manager_service.py\", line 364, in get_model\r\n    model_info = self.mgr.get_model(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_manager.py\", line 484, in get_model\r\n    model_path = model_class.convert_if_required(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\sdxl.py\", line 118, in convert_if_required\r\n    return _convert_ckpt_and_cache(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\stable_diffusion.py\", line 282, in _convert_ckpt_and_cache\r\n    convert_ckpt_to_diffusers(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\convert_ckpt_to_diffusers.py\", line 1726, in convert_ckpt_to_diffusers\r\n    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\convert_ckpt_to_diffusers.py\", line 1397, in download_from_original_stable_diffusion_ckpt\r\n    converted_unet_checkpoint = convert_ldm_unet_checkpoint(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\convert_ckpt_to_diffusers.py\", line 440, in convert_ldm_unet_checkpoint\r\n    new_checkpoint[\"time_embedding.linear_1.weight\"] = unet_state_dict[\"time_embed.0.weight\"]\r\nKeyError: 'time_embed.0.weight'\r\n\r\n[2023-07-28 08:46:59,688]::[InvokeAI]::ERROR --> Error while invoking:\r\n'time_embed.0.weight'\r\n\r\n===================================================\r\n#2 error\r\n================================================================\r\n[2023-07-28 09:16:04,888]::[InvokeAI]::ERROR --> Traceback (most recent call last):\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\processor.py\", line 86, in __process\r\n    outputs = invocation.invoke(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\compel.py\", line 352, in invoke\r\n    c1, c1_pooled, ec1 = self.run_clip_compel(context, self.clip, self.prompt, False)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\compel.py\", line 243, in run_clip_compel\r\n    tokenizer_info = context.services.model_manager.get_model(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\app\\services\\model_manager_service.py\", line 364, in get_model\r\n    model_info = self.mgr.get_model(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\model_manager.py\", line 484, in get_model\r\n    model_path = model_class.convert_if_required(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\sdxl.py\", line 118, in convert_if_required\r\n    return _convert_ckpt_and_cache(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\models\\stable_diffusion.py\", line 282, in _convert_ckpt_and_cache\r\n    convert_ckpt_to_diffusers(\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\convert_ckpt_to_diffusers.py\", line 1726, in convert_ckpt_to_diffusers\r\n    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\invokeai\\backend\\model_management\\convert_ckpt_to_diffusers.py\", line 1407, in download_from_original_stable_diffusion_ckpt\r\n    set_module_tensor_to_device(unet, param_name, \"cpu\", value=param)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\accelerate\\utils\\modeling.py\", line 255, in set_module_tensor_to_device\r\n    new_module = getattr(module, split)\r\n  File \"E:\\data\\invoke3\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1614, in __getattr__\r\n    raise AttributeError(\"'{}' object has no attribute '{}'\".format(\r\nAttributeError: 'ModuleList' object has no attribute '1'\r\n\r\n[2023-07-28 09:16:04,888]::[InvokeAI]::ERROR --> Error while invoking:\r\n'ModuleList' object has no attribute '1'\r\n\r\n### Contact Details\r\n\r\ndavidf@argus-holdings.com",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1781391321",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4050#issuecomment-1781391321",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4050",
                "id": 1781391321,
                "node_id": "IC_kwDOH1Ppo85qLd_Z",
                "user": {
                    "login": "gingerkrueger",
                    "id": 126418078,
                    "node_id": "U_kgDOB4j8ng",
                    "avatar_url": "https://avatars.githubusercontent.com/u/126418078?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/gingerkrueger",
                    "html_url": "https://github.com/gingerkrueger",
                    "followers_url": "https://api.github.com/users/gingerkrueger/followers",
                    "following_url": "https://api.github.com/users/gingerkrueger/following{/other_user}",
                    "gists_url": "https://api.github.com/users/gingerkrueger/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/gingerkrueger/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/gingerkrueger/subscriptions",
                    "organizations_url": "https://api.github.com/users/gingerkrueger/orgs",
                    "repos_url": "https://api.github.com/users/gingerkrueger/repos",
                    "events_url": "https://api.github.com/users/gingerkrueger/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/gingerkrueger/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-26T15:48:56Z",
                "updated_at": "2023-10-26T15:48:56Z",
                "author_association": "NONE",
                "body": "Having the same issue, has anyone had an update on this?",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1781391321/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-26T15:48:57Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32873301788",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 149089618,
            "login": "This-is-New1",
            "display_login": "This-is-New1",
            "gravatar_id": "",
            "url": "https://api.github.com/users/This-is-New1",
            "avatar_url": "https://avatars.githubusercontent.com/u/149089618?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4943",
                "id": 1949912659,
                "node_id": "I_kwDOH1Ppo850OU5T",
                "number": 4943,
                "title": "[bug]: ControlNet Error",
                "user": {
                    "login": "AbedAchai1",
                    "id": 136920434,
                    "node_id": "U_kgDOCCk9cg",
                    "avatar_url": "https://avatars.githubusercontent.com/u/136920434?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/AbedAchai1",
                    "html_url": "https://github.com/AbedAchai1",
                    "followers_url": "https://api.github.com/users/AbedAchai1/followers",
                    "following_url": "https://api.github.com/users/AbedAchai1/following{/other_user}",
                    "gists_url": "https://api.github.com/users/AbedAchai1/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/AbedAchai1/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/AbedAchai1/subscriptions",
                    "organizations_url": "https://api.github.com/users/AbedAchai1/orgs",
                    "repos_url": "https://api.github.com/users/AbedAchai1/repos",
                    "events_url": "https://api.github.com/users/AbedAchai1/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/AbedAchai1/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402082,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY4g",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/bug",
                        "name": "bug",
                        "color": "d73a4a",
                        "default": true,
                        "description": "Something isn't working"
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 3,
                "created_at": "2023-10-18T14:34:27Z",
                "updated_at": "2023-10-26T15:17:58Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "### Is there an existing issue for this?\n\n- [X] I have searched the existing issues\n\n### OS\n\nWindows\n\n### GPU\n\ncpu\n\n### VRAM\n\n12GB\n\n### What version did you experience this issue on?\n\n3.3.0\n\n### What happened?\n\nWhen I uploaded an image on Controlnet suddenly the image was loading continuously in the history, it looked like it was in a loop continuously loading the image\n\n### Screenshots\n\n![image](https://github.com/invoke-ai/InvokeAI/assets/136920434/0d4a8156-a580-498f-9308-491e7ee9c03d)\r\n![image2](https://github.com/invoke-ai/InvokeAI/assets/136920434/eaeba5e5-3791-425c-9411-7a0fd05194da)\r\n![image3](https://github.com/invoke-ai/InvokeAI/assets/136920434/f2986d7e-3a7b-4cb2-a5ea-23d62f5f6e3c)\r\n![image4](https://github.com/invoke-ai/InvokeAI/assets/136920434/490f1b7a-acbf-40bf-9bc3-352ec0847236)\r\n\n\n### Additional context\n\n_No response_\n\n### Contact Details\n\nabedachai@gmail.com",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1781336533",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4943#issuecomment-1781336533",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4943",
                "id": 1781336533,
                "node_id": "IC_kwDOH1Ppo85qLQnV",
                "user": {
                    "login": "This-is-New1",
                    "id": 149089618,
                    "node_id": "U_kgDOCOLtUg",
                    "avatar_url": "https://avatars.githubusercontent.com/u/149089618?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/This-is-New1",
                    "html_url": "https://github.com/This-is-New1",
                    "followers_url": "https://api.github.com/users/This-is-New1/followers",
                    "following_url": "https://api.github.com/users/This-is-New1/following{/other_user}",
                    "gists_url": "https://api.github.com/users/This-is-New1/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/This-is-New1/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/This-is-New1/subscriptions",
                    "organizations_url": "https://api.github.com/users/This-is-New1/orgs",
                    "repos_url": "https://api.github.com/users/This-is-New1/repos",
                    "events_url": "https://api.github.com/users/This-is-New1/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/This-is-New1/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-26T15:17:58Z",
                "updated_at": "2023-10-26T15:17:58Z",
                "author_association": "NONE",
                "body": "Same issue here. When running invokeai via google colab I often stumble upon this kind of error/bug.\r\nIt just perpetually on \"loading\" state within logs history whenever I tried to upload an image into the controlNet form.\r\nI've tried changing the processor, such as midas & other while in depth controlNet but to no avail.\r\n\r\nAlso weirdly enough, whenever I'm done generating an image it won't shows up and stay on loading unless I refreshed the UI page while in logs history it just shows the same loop as if I was try to load the controlNet.\r\nThis force me to generate one image at a time & can't generate in a batch.\r\n\r\nHope these issue can be resolved.",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1781336533/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-26T15:17:59Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32871301108",
        "type": "WatchEvent",
        "actor": {
            "id": 32405217,
            "login": "cmhamiche",
            "display_login": "cmhamiche",
            "gravatar_id": "",
            "url": "https://api.github.com/users/cmhamiche",
            "avatar_url": "https://avatars.githubusercontent.com/u/32405217?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T14:18:28Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32869629705",
        "type": "ForkEvent",
        "actor": {
            "id": 23297541,
            "login": "thethao133",
            "display_login": "thethao133",
            "gravatar_id": "",
            "url": "https://api.github.com/users/thethao133",
            "avatar_url": "https://avatars.githubusercontent.com/u/23297541?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "forkee": {
                "id": 710327975,
                "node_id": "R_kgDOKla-pw",
                "name": "InvokeAI",
                "full_name": "thethao133/InvokeAI",
                "private": false,
                "owner": {
                    "login": "thethao133",
                    "id": 23297541,
                    "node_id": "MDQ6VXNlcjIzMjk3NTQx",
                    "avatar_url": "https://avatars.githubusercontent.com/u/23297541?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/thethao133",
                    "html_url": "https://github.com/thethao133",
                    "followers_url": "https://api.github.com/users/thethao133/followers",
                    "following_url": "https://api.github.com/users/thethao133/following{/other_user}",
                    "gists_url": "https://api.github.com/users/thethao133/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/thethao133/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/thethao133/subscriptions",
                    "organizations_url": "https://api.github.com/users/thethao133/orgs",
                    "repos_url": "https://api.github.com/users/thethao133/repos",
                    "events_url": "https://api.github.com/users/thethao133/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/thethao133/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "html_url": "https://github.com/thethao133/InvokeAI",
                "description": "InvokeAI is a leading creative engine for Stable Diffusion models, empowering professionals, artists, and enthusiasts to generate and create visual media using the latest AI-driven technologies. The solution offers an industry leading WebUI, supports terminal use through a CLI, and serves as the foundation for multiple commercial products.",
                "fork": true,
                "url": "https://api.github.com/repos/thethao133/InvokeAI",
                "forks_url": "https://api.github.com/repos/thethao133/InvokeAI/forks",
                "keys_url": "https://api.github.com/repos/thethao133/InvokeAI/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/thethao133/InvokeAI/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/thethao133/InvokeAI/teams",
                "hooks_url": "https://api.github.com/repos/thethao133/InvokeAI/hooks",
                "issue_events_url": "https://api.github.com/repos/thethao133/InvokeAI/issues/events{/number}",
                "events_url": "https://api.github.com/repos/thethao133/InvokeAI/events",
                "assignees_url": "https://api.github.com/repos/thethao133/InvokeAI/assignees{/user}",
                "branches_url": "https://api.github.com/repos/thethao133/InvokeAI/branches{/branch}",
                "tags_url": "https://api.github.com/repos/thethao133/InvokeAI/tags",
                "blobs_url": "https://api.github.com/repos/thethao133/InvokeAI/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/thethao133/InvokeAI/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/thethao133/InvokeAI/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/thethao133/InvokeAI/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/thethao133/InvokeAI/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/thethao133/InvokeAI/languages",
                "stargazers_url": "https://api.github.com/repos/thethao133/InvokeAI/stargazers",
                "contributors_url": "https://api.github.com/repos/thethao133/InvokeAI/contributors",
                "subscribers_url": "https://api.github.com/repos/thethao133/InvokeAI/subscribers",
                "subscription_url": "https://api.github.com/repos/thethao133/InvokeAI/subscription",
                "commits_url": "https://api.github.com/repos/thethao133/InvokeAI/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/thethao133/InvokeAI/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/thethao133/InvokeAI/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/thethao133/InvokeAI/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/thethao133/InvokeAI/contents/{+path}",
                "compare_url": "https://api.github.com/repos/thethao133/InvokeAI/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/thethao133/InvokeAI/merges",
                "archive_url": "https://api.github.com/repos/thethao133/InvokeAI/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/thethao133/InvokeAI/downloads",
                "issues_url": "https://api.github.com/repos/thethao133/InvokeAI/issues{/number}",
                "pulls_url": "https://api.github.com/repos/thethao133/InvokeAI/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/thethao133/InvokeAI/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/thethao133/InvokeAI/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/thethao133/InvokeAI/labels{/name}",
                "releases_url": "https://api.github.com/repos/thethao133/InvokeAI/releases{/id}",
                "deployments_url": "https://api.github.com/repos/thethao133/InvokeAI/deployments",
                "created_at": "2023-10-26T13:29:38Z",
                "updated_at": "2023-10-26T13:29:38Z",
                "pushed_at": "2023-10-24T21:28:51Z",
                "git_url": "git://github.com/thethao133/InvokeAI.git",
                "ssh_url": "git@github.com:thethao133/InvokeAI.git",
                "clone_url": "https://github.com/thethao133/InvokeAI.git",
                "svn_url": "https://github.com/thethao133/InvokeAI",
                "homepage": "https://invoke-ai.github.io/InvokeAI/",
                "size": 274790,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": null,
                "has_issues": false,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 0,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "main",
                "public": true
            }
        },
        "public": true,
        "created_at": "2023-10-26T13:29:39Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32867518703",
        "type": "WatchEvent",
        "actor": {
            "id": 144891332,
            "login": "smilebacki",
            "display_login": "smilebacki",
            "gravatar_id": "",
            "url": "https://api.github.com/users/smilebacki",
            "avatar_url": "https://avatars.githubusercontent.com/u/144891332?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T12:24:37Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32864836881",
        "type": "WatchEvent",
        "actor": {
            "id": 73317878,
            "login": "Gerome100",
            "display_login": "Gerome100",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Gerome100",
            "avatar_url": "https://avatars.githubusercontent.com/u/73317878?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T10:45:02Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32864261499",
        "type": "WatchEvent",
        "actor": {
            "id": 545228,
            "login": "Jensen2k",
            "display_login": "Jensen2k",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Jensen2k",
            "avatar_url": "https://avatars.githubusercontent.com/u/545228?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T10:24:08Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32863956131",
        "type": "IssueCommentEvent",
        "actor": {
            "id": 303100,
            "login": "GreggHelt2",
            "display_login": "GreggHelt2",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GreggHelt2",
            "avatar_url": "https://avatars.githubusercontent.com/u/303100?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951",
                "repository_url": "https://api.github.com/repos/invoke-ai/InvokeAI",
                "labels_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951/labels{/name}",
                "comments_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951/comments",
                "events_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951/events",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4951",
                "id": 1951531925,
                "node_id": "I_kwDOH1Ppo850UgOV",
                "number": 4951,
                "title": "Latent Consistency Model Support",
                "user": {
                    "login": "Millu",
                    "id": 7254508,
                    "node_id": "MDQ6VXNlcjcyNTQ1MDg=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/7254508?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Millu",
                    "html_url": "https://github.com/Millu",
                    "followers_url": "https://api.github.com/users/Millu/followers",
                    "following_url": "https://api.github.com/users/Millu/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Millu/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Millu/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Millu/subscriptions",
                    "organizations_url": "https://api.github.com/users/Millu/orgs",
                    "repos_url": "https://api.github.com/users/Millu/repos",
                    "events_url": "https://api.github.com/users/Millu/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Millu/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 4433402085,
                        "node_id": "LA_kwDOH1Ppo88AAAABCEBY5Q",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/enhancement",
                        "name": "enhancement",
                        "color": "a2eeef",
                        "default": true,
                        "description": "New feature or request"
                    },
                    {
                        "id": 5491012391,
                        "node_id": "LA_kwDOH1Ppo88AAAABR0ozJw",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/model%20manager",
                        "name": "model manager",
                        "color": "89CF80",
                        "default": false,
                        "description": ""
                    },
                    {
                        "id": 5817593882,
                        "node_id": "LA_kwDOH1Ppo88AAAABWsFwGg",
                        "url": "https://api.github.com/repos/invoke-ai/InvokeAI/labels/image%20generation",
                        "name": "image generation",
                        "color": "6BE2DC",
                        "default": false,
                        "description": ""
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 1,
                "created_at": "2023-10-19T07:56:19Z",
                "updated_at": "2023-10-26T10:13:42Z",
                "closed_at": null,
                "author_association": "COLLABORATOR",
                "active_lock_reason": null,
                "body": "## Summary \nThe Latent Consistency Model allows for coherent generations with very low step counts (<5 steps) with efficient generation speeds\n\n## Intended Outcome\n* Latent Consistency Model is able to be used with InvokeAI \n* Benefits of the model are experienced\n",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951/reactions",
                    "total_count": 1,
                    "+1": 1,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            },
            "comment": {
                "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1780820872",
                "html_url": "https://github.com/invoke-ai/InvokeAI/issues/4951#issuecomment-1780820872",
                "issue_url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/4951",
                "id": 1780820872,
                "node_id": "IC_kwDOH1Ppo85qJSuI",
                "user": {
                    "login": "GreggHelt2",
                    "id": 303100,
                    "node_id": "MDQ6VXNlcjMwMzEwMA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/303100?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/GreggHelt2",
                    "html_url": "https://github.com/GreggHelt2",
                    "followers_url": "https://api.github.com/users/GreggHelt2/followers",
                    "following_url": "https://api.github.com/users/GreggHelt2/following{/other_user}",
                    "gists_url": "https://api.github.com/users/GreggHelt2/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/GreggHelt2/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/GreggHelt2/subscriptions",
                    "organizations_url": "https://api.github.com/users/GreggHelt2/orgs",
                    "repos_url": "https://api.github.com/users/GreggHelt2/repos",
                    "events_url": "https://api.github.com/users/GreggHelt2/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/GreggHelt2/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "created_at": "2023-10-26T10:13:42Z",
                "updated_at": "2023-10-26T10:13:42Z",
                "author_association": "COLLABORATOR",
                "body": "@Millu I just posted on InvokeAI Discord about a proof-of-concept node for testing Latent Consistency Models in Node UI:\r\nhttps://discord.com/channels/1020123559063990373/1167039417962217574/1167039417962217574\r\n\r\n",
                "reactions": {
                    "url": "https://api.github.com/repos/invoke-ai/InvokeAI/issues/comments/1780820872/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "performed_via_github_app": null
            }
        },
        "public": true,
        "created_at": "2023-10-26T10:13:42Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32858044001",
        "type": "WatchEvent",
        "actor": {
            "id": 115113311,
            "login": "modball",
            "display_login": "modball",
            "gravatar_id": "",
            "url": "https://api.github.com/users/modball",
            "avatar_url": "https://avatars.githubusercontent.com/u/115113311?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T06:38:07Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    },
    {
        "id": "32857201080",
        "type": "WatchEvent",
        "actor": {
            "id": 92154369,
            "login": "FranciscoJustoDev",
            "display_login": "FranciscoJustoDev",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FranciscoJustoDev",
            "avatar_url": "https://avatars.githubusercontent.com/u/92154369?"
        },
        "repo": {
            "id": 525592995,
            "name": "invoke-ai/InvokeAI",
            "url": "https://api.github.com/repos/invoke-ai/InvokeAI"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T05:54:44Z",
        "org": {
            "id": 113954515,
            "login": "invoke-ai",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/invoke-ai",
            "avatar_url": "https://avatars.githubusercontent.com/u/113954515?"
        }
    }
]