[
    {
        "id": "32885375382",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3112",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3112/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3112/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3112/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3112",
                "id": 1964590400,
                "node_id": "I_kwDOBqp6lM51GUVA",
                "number": 3112,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-27T01:03:34Z",
                "updated_at": "2023-10-27T01:03:35Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6661089624\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3112/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3112/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-27T01:03:36Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32873573493",
        "type": "WatchEvent",
        "actor": {
            "id": 39435372,
            "login": "andrewc01",
            "display_login": "andrewc01",
            "gravatar_id": "",
            "url": "https://api.github.com/users/andrewc01",
            "avatar_url": "https://avatars.githubusercontent.com/u/39435372?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-26T15:26:40Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32852867379",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3111",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3111/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3111/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3111/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3111",
                "id": 1962509649,
                "node_id": "I_kwDOBqp6lM50-YVR",
                "number": 3111,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-26T00:38:38Z",
                "updated_at": "2023-10-26T00:38:39Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6647592414\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3111/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3111/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-26T00:38:40Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32820170309",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3110",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3110/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3110/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3110/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3110",
                "id": 1960323821,
                "node_id": "I_kwDOBqp6lM502Crt",
                "number": 3110,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-25T01:06:56Z",
                "updated_at": "2023-10-25T01:06:56Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6633910893\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3110/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3110/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-25T01:06:57Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32803187969",
        "type": "WatchEvent",
        "actor": {
            "id": 5833256,
            "login": "OutSorcerer",
            "display_login": "OutSorcerer",
            "gravatar_id": "",
            "url": "https://api.github.com/users/OutSorcerer",
            "avatar_url": "https://avatars.githubusercontent.com/u/5833256?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-24T12:55:13Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32790037682",
        "type": "WatchEvent",
        "actor": {
            "id": 37576309,
            "login": "Holmestime",
            "display_login": "Holmestime",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Holmestime",
            "avatar_url": "https://avatars.githubusercontent.com/u/37576309?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-24T02:25:31Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32790034609",
        "type": "WatchEvent",
        "actor": {
            "id": 32810927,
            "login": "whq2017",
            "display_login": "whq2017",
            "gravatar_id": "",
            "url": "https://api.github.com/users/whq2017",
            "avatar_url": "https://avatars.githubusercontent.com/u/32810927?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-24T02:25:17Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789047112",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3108",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3108",
                "id": 1956153428,
                "node_id": "I_kwDOBqp6lM50mIhU",
                "number": 3108,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-23T01:03:39Z",
                "updated_at": "2023-10-24T01:16:38Z",
                "closed_at": "2023-10-24T01:16:38Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6606994965\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3108/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:39Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046994",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3107",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3107",
                "id": 1955716383,
                "node_id": "I_kwDOBqp6lM50kd0f",
                "number": 3107,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-22T01:03:31Z",
                "updated_at": "2023-10-24T01:16:38Z",
                "closed_at": "2023-10-24T01:16:37Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6600398816\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3107/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:38Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046909",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3106",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3106",
                "id": 1955181781,
                "node_id": "I_kwDOBqp6lM50ibTV",
                "number": 3106,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-21T01:03:55Z",
                "updated_at": "2023-10-24T01:16:37Z",
                "closed_at": "2023-10-24T01:16:37Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6593849076\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3106/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:38Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046826",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3105",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3105/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3105/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3105/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3105",
                "id": 1953298708,
                "node_id": "I_kwDOBqp6lM50bPkU",
                "number": 3105,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-20T01:06:10Z",
                "updated_at": "2023-10-24T01:16:37Z",
                "closed_at": "2023-10-24T01:16:37Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6581575632\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3105/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3105/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:37Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046747",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3103",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3103/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3103/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3103/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3103",
                "id": 1950974151,
                "node_id": "I_kwDOBqp6lM50SYDH",
                "number": 3103,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-19T00:39:35Z",
                "updated_at": "2023-10-24T01:16:36Z",
                "closed_at": "2023-10-24T01:16:36Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit f179a439b38d2feaab310a1fdb6547a03a27d534**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6567971409\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3103/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3103/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:37Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046661",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3100",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3100/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3100/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3100/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3100",
                "id": 1948549877,
                "node_id": "I_kwDOBqp6lM50JIL1",
                "number": 3100,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-18T01:05:36Z",
                "updated_at": "2023-10-24T01:16:36Z",
                "closed_at": "2023-10-24T01:16:36Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit f3124c9a650ba9ce8247f21c4c05290ba4fddbad**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6554271731\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3100/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3100/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:37Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046560",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3098",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3098/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3098/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3098/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3098",
                "id": 1946334014,
                "node_id": "I_kwDOBqp6lM50ArM-",
                "number": 3098,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-17T01:02:27Z",
                "updated_at": "2023-10-24T01:16:36Z",
                "closed_at": "2023-10-24T01:16:35Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 624eb6368d48cbda9a270758b4ec5106a69140a2**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6540671675\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3098/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3098/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:36Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046473",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3094",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3094/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3094/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3094/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3094",
                "id": 1944154082,
                "node_id": "I_kwDOBqp6lM5z4W_i",
                "number": 3094,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-16T01:05:53Z",
                "updated_at": "2023-10-24T01:16:35Z",
                "closed_at": "2023-10-24T01:16:35Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 253b5f1ace360f707ea348d1bd9c4e5f96887bbf**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6527270672\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3094/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3094/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:36Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046391",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3093",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3093/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3093/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3093/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3093",
                "id": 1942845442,
                "node_id": "I_kwDOBqp6lM5zzXgC",
                "number": 3093,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-14T01:02:50Z",
                "updated_at": "2023-10-24T01:16:35Z",
                "closed_at": "2023-10-24T01:16:35Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 253b5f1ace360f707ea348d1bd9c4e5f96887bbf**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6514195060\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3093/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3093/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:35Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046294",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3092",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3092/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3092/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3092/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3092",
                "id": 1939558040,
                "node_id": "I_kwDOBqp6lM5zm06Y",
                "number": 3092,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-12T09:12:38Z",
                "updated_at": "2023-10-24T01:16:34Z",
                "closed_at": "2023-10-24T01:16:34Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 45b11c4c3bc59bd24478fbf04a7707c1e4c4c067**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6493330604\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3092/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3092/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:35Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046187",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3090",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3090/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3090/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3090/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3090",
                "id": 1938979068,
                "node_id": "I_kwDOBqp6lM5zknj8",
                "number": 3090,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-12T00:49:33Z",
                "updated_at": "2023-10-24T01:16:34Z",
                "closed_at": "2023-10-24T01:16:34Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 854b5ea91629aefc5ab6fc35b5990190e3b35178**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6489413614\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3090/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3090/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:35Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045912",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3084",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3084/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3084/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3084/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3084",
                "id": 1927852881,
                "node_id": "I_kwDOBqp6lM5y6LNR",
                "number": 3084,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-05T09:48:09Z",
                "updated_at": "2023-10-24T01:16:33Z",
                "closed_at": "2023-10-24T01:16:33Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit ecf117ccadc3970a05c61d2013a8a7039aac1b34**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6417092954\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3084/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3084/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:33Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789046088",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3088",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3088/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3088/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3088/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3088",
                "id": 1934090026,
                "node_id": "I_kwDOBqp6lM5zR98q",
                "number": 3088,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-10T01:02:47Z",
                "updated_at": "2023-10-24T01:16:33Z",
                "closed_at": "2023-10-24T01:16:33Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit f26078f89a25fee11059af61e17d45a17372fad3**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6462932147\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3088/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3088/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:34Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045990",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3085",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3085/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3085/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3085/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3085",
                "id": 1929102485,
                "node_id": "I_kwDOBqp6lM5y-8SV",
                "number": 3085,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-05T21:40:21Z",
                "updated_at": "2023-10-24T01:16:33Z",
                "closed_at": "2023-10-24T01:16:33Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit dbbbd8c0f2198d5d513058c83853f132b245ae34**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6424252884\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3085/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3085/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:34Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045844",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3083",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3083/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3083/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3083/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3083",
                "id": 1927178119,
                "node_id": "I_kwDOBqp6lM5y3meH",
                "number": 3083,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-05T00:37:08Z",
                "updated_at": "2023-10-24T01:16:32Z",
                "closed_at": "2023-10-24T01:16:32Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit e95e6ec5267c3ce5d90c2b7fe4c9585c1ac8b0a5**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6412871073\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3083/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3083/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:33Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045738",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3082",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3082/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3082/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3082/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3082",
                "id": 1925690800,
                "node_id": "I_kwDOBqp6lM5yx7Ww",
                "number": 3082,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-04T08:36:52Z",
                "updated_at": "2023-10-24T01:16:32Z",
                "closed_at": "2023-10-24T01:16:32Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 6c27dbc04147c6f6fd492cb54c3f1f97df4bb24b**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6403295233\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3082/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3082/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:33Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045652",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3077",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3077/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3077/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3077/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3077",
                "id": 1925187456,
                "node_id": "I_kwDOBqp6lM5ywAeA",
                "number": 3077,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-04T00:50:13Z",
                "updated_at": "2023-10-24T01:16:31Z",
                "closed_at": "2023-10-24T01:16:31Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit b8751f2c4606d305383382d71bbae067ec8067e8**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6399742636\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3077/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3077/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:32Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32789045567",
        "type": "IssuesEvent",
        "actor": {
            "id": 2459423,
            "login": "vfdev-5",
            "display_login": "vfdev-5",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vfdev-5",
            "avatar_url": "https://avatars.githubusercontent.com/u/2459423?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "closed",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3073",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3073/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3073/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3073/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3073",
                "id": 1914504924,
                "node_id": "I_kwDOBqp6lM5yHQbc",
                "number": 3073,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "closed",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-09-27T01:02:36Z",
                "updated_at": "2023-10-24T01:16:31Z",
                "closed_at": "2023-10-24T01:16:31Z",
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 018fa5b9a8bc74512d072f9d5de0bf80cd6d2744**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6319603679\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3073/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3073/timeline",
                "performed_via_github_app": null,
                "state_reason": "completed"
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:16:32Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32788904213",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3109",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3109/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3109/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3109/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3109",
                "id": 1958280016,
                "node_id": "I_kwDOBqp6lM50uPtQ",
                "number": 3109,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-24T01:06:17Z",
                "updated_at": "2023-10-24T01:06:17Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6620437333\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3109/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3109/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-24T01:06:18Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32756944667",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3108",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3108",
                "id": 1956153428,
                "node_id": "I_kwDOBqp6lM50mIhU",
                "number": 3108,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-23T01:03:39Z",
                "updated_at": "2023-10-23T01:03:39Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6606994965\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3108/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3108/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-23T01:03:40Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32746693551",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3107",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3107",
                "id": 1955716383,
                "node_id": "I_kwDOBqp6lM50kd0f",
                "number": 3107,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-22T01:03:31Z",
                "updated_at": "2023-10-22T01:03:31Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6600398816\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3107/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3107/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-22T01:03:32Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32736707290",
        "type": "IssuesEvent",
        "actor": {
            "id": 41898282,
            "login": "github-actions[bot]",
            "display_login": "github-actions",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions[bot]",
            "avatar_url": "https://avatars.githubusercontent.com/u/41898282?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "opened",
            "issue": {
                "url": "https://api.github.com/repos/pytorch/ignite/issues/3106",
                "repository_url": "https://api.github.com/repos/pytorch/ignite",
                "labels_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/labels{/name}",
                "comments_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/comments",
                "events_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/events",
                "html_url": "https://github.com/pytorch/ignite/issues/3106",
                "id": 1955181781,
                "node_id": "I_kwDOBqp6lM50ibTV",
                "number": 3106,
                "title": "Scheduled workflow failed",
                "user": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": false
                },
                "labels": [
                    {
                        "id": 759300263,
                        "node_id": "MDU6TGFiZWw3NTkzMDAyNjM=",
                        "url": "https://api.github.com/repos/pytorch/ignite/labels/bug",
                        "name": "bug",
                        "color": "ee0701",
                        "default": true,
                        "description": null
                    }
                ],
                "state": "open",
                "locked": false,
                "assignee": null,
                "assignees": [],
                "milestone": null,
                "comments": 0,
                "created_at": "2023-10-21T01:03:55Z",
                "updated_at": "2023-10-21T01:03:56Z",
                "closed_at": null,
                "author_association": "NONE",
                "active_lock_reason": null,
                "body": "Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 47b95d087a0f8713a9d24bcfe3a539b08101ba7a**.\nPlease look into it:\n\nhttps://github.com/pytorch/ignite/actions/runs/6593849076\n\nFeel free to close this if this was just a one-off error.\n",
                "reactions": {
                    "url": "https://api.github.com/repos/pytorch/ignite/issues/3106/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0
                },
                "timeline_url": "https://api.github.com/repos/pytorch/ignite/issues/3106/timeline",
                "performed_via_github_app": null,
                "state_reason": null
            }
        },
        "public": true,
        "created_at": "2023-10-21T01:03:57Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    },
    {
        "id": "32731959557",
        "type": "WatchEvent",
        "actor": {
            "id": 8289812,
            "login": "3tty0n",
            "display_login": "3tty0n",
            "gravatar_id": "",
            "url": "https://api.github.com/users/3tty0n",
            "avatar_url": "https://avatars.githubusercontent.com/u/8289812?"
        },
        "repo": {
            "id": 111835796,
            "name": "pytorch/ignite",
            "url": "https://api.github.com/repos/pytorch/ignite"
        },
        "payload": {
            "action": "started"
        },
        "public": true,
        "created_at": "2023-10-20T19:16:59Z",
        "org": {
            "id": 21003710,
            "login": "pytorch",
            "gravatar_id": "",
            "url": "https://api.github.com/orgs/pytorch",
            "avatar_url": "https://avatars.githubusercontent.com/u/21003710?"
        }
    }
]